#!/bin/sh
# Copyright (C) 2013 Ben Asselstine
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

#here is what we expect
expected=`mktemp $builddir/licensing.XXXXXX`
cat << EOF > $expected
foo
EOF

#generating our results
cat << EOF | $licensing uncomment --trim
/*******
* foo *
*******/
EOF

#0004.log is simultaneously created as this script runs.
diff -uNrd $expected $builddir/0004.log
retval=$?

#cleanup
rm $expected
exit $retval
