#!/bin/sh
# Copyright (C) 2013 Ben Asselstine
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

#here is what we expect
expected=`mktemp $builddir/licensing.XXXXXX`
cat << EOF > $expected
#!/bin/bash
#foo
echo bar
EOF

#this is the SOURCE file in the prepend command
src=`mktemp $builddir/licensing.XXXXXX`
echo "#foo" > $src

#this is the DEST file in the prepend command
dst=`mktemp $builddir/licensing.XXXXXX`
cat << EOF > $dst
#!/bin/bash
echo bar
EOF

#generating our results
$licensing prepend $src $dst --no-backup
cat $dst

#0001.log is simultaneously created as this script runs.
diff -uNrd $expected $builddir/0001.log
retval=$?

#cleanup
rm $expected
rm $src
rm $dst

exit $retval
