#!/bin/sh
# Copyright (C) 2013 Ben Asselstine
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

#here is what we expect
expected=`mktemp $builddir/licensing.XXXXXX`
echo "foo bar" > $expected

#generating our results
$licensing top foo bar --quiet
cat ${HOME}/.licenseutils/top-line

#0001.log is simultaneously created as this script runs.
diff -uNrd $expected $builddir/0001.log
retval=$?

#cleanup
rm $expected
rm ${HOME}/.licenseutils/top-line
rmdir ${HOME}/.licenseutils

exit $retval
